steps:
  # Étape 1 : Build de l'image Docker (PLUS AUCUNE CLÉ REQUISE AU BUILD)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/storkquiz-platform:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/storkquiz-platform:latest'
      - '.'

  # Étape 2 : Push de l'image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storkquiz-platform:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storkquiz-platform:latest']

  # Étape 3 : Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'storkquiz-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/storkquiz-platform:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/storkquiz-platform:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/storkquiz-platform:latest'
